# Generated by Django 5.1.7 on 2025-03-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='scores',
            field=models.JSONField(),
        ),
    ]
