# Generated by Django 5.2 on 2025-04-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id_available',
            new_name='is_available',
        ),
    ]
